/*
 * File: app/view/ui/DashboardPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.view.ui.DashboardPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashboardpanel',

    itemId: 'panelDashboard',
    layout: {
        align: 'center',
        pack: 'center',
        type: 'vbox'
    },
    bodyBorder: false,
    bodyStyle: 'background-color: transparent !important;',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    cls: 'sys-toolbar',
                    itemId: 'dashboardToolbar',
                    items: [
                        {
                            xtype: 'container',
                            cls: 'logo',
                            height: 50,
                            itemId: 'ctLogo',
                            style: {
                                backgroundColor: '#ECECEC'
                            },
                            width: 214
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'splitbutton',
                            itemId: 'btnUsuario',
                            iconCls: 'icon-user',
                            text: 'Usuário',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        itemId: 'btnTrocaSenha',
                                        text: 'Trocar senha'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSair',
                            iconCls: 'icon-exit',
                            scale: 'medium',
                            text: 'Sair'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 1,
                    itemId: 'ctSeparator',
                    style: 'background-color: #fff;'
                }
            ]
        });

        me.callParent(arguments);
    }

});