/*
 * File: app/controller/ui/DashboardController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.controller.ui.DashboardController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'uiViewport',
            selector: 'uiviewport',
            xtype: 'Ext.container.Viewport'
        },
        {
            ref: 'changePassWindow',
            selector: 'changepasswindow',
            xtype: 'Ext.window.Window'
        }
    ],

    exitClick: function(button, e, eOpts) {
        Ext.Msg.confirm('Confirme', 'Deseja realmente sair do sistema?', function(btn){
            if ('yes' == btn){
                Actions.NetonApp_Security.logout({}, function(response){
                location.reload();
            });
        }
    },this);
    },

    onDashboardShow: function(component, eOpts) {
        var session = this.application.getSession();

        component.down('#btnUsuario').setText(session['user.name']).doComponentLayout();
    },

    onTrocaSenhaClick: function(button, e, eOpts) {
        var win = Ext.widget('changepasswindow');

        win.show();
    },

    onChangePassShow: function(component, eOpts) {
        component.down('#txtSenha').focus(false, 250);
    },

    changePassFocusNextField: function(textfield, e, eOpts) {
        if (e.getKey() == 13){
            try{
                textfield.nextNode().focus();
            } catch(e){
                if (textfield.up('form').isValid())
                this.requestChangePass();
            }
        }
    },

    changePassConfirmarTrocaClick: function(button, e, eOpts) {
        this.requestChangePass();
    },

    changePassCancelarClick: function(button, e, eOpts) {
        this.getChangePassWindow().close();
    },

    showDashboardPanel: function() {
        var viewport = this.getUiViewport();

        Actions.NetonApp_Security.isLogged({}, function(response){

        if (response != false){
            this.application.setSession(response);

            if (!viewport.down('#panelDashboard')){    
                viewport.add({
                    xtype: 'dashboardpanel',
                    itemId: 'panelDashboard'
                });    
            }

            this.getUiViewport().getLayout().setActiveItem('panelDashboard');            
        }
    },this);
    },

    requestChangePass: function() {
        var me = this,
            win = me.getChangePassWindow();

        win.setLoading('Aguarde...');

        Actions.NetonApp_Security.changePass(win.down('#form').getValues(), me.responseChangePass, me);
    },

    responseChangePass: function(response) {
        var me = this,
            win = me.getChangePassWindow();

        // se a troca de senha ocorreu com sucesso
        if (response){
            // fecha a janela
            win.close();

            // exibe mensagem de sucesso na troca de senha
            Neton.Msg.flash({
                type: 'success',
                msg: 'Senha alterada com sucesso!',
                width: 250
            });
        } else { // se não foi possível trocar a senha
            // fecha a máscara de carregamento
            win.setLoading(false);

            // exibe mensagem de erro
            Neton.Msg.flash({
                type: 'error',
                msg: 'A senha atual está incorreta!',
                width: 250,
                callback: function(){
                    win.down('#txtSenha').focus(true);
                }
            });
        }
    },

    init: function(application) {
        this.control({
            "dashboardpanel #btnSair": {
                click: this.exitClick
            },
            "dashboardpanel": {
                show: this.onDashboardShow
            },
            "dashboardpanel #btnTrocaSenha": {
                click: this.onTrocaSenhaClick
            },
            "changepasswindow": {
                show: this.onChangePassShow
            },
            "changepasswindow #form field": {
                keypress: this.changePassFocusNextField
            },
            "changepasswindow #btnConfirmar": {
                click: this.changePassConfirmarTrocaClick
            },
            "changepasswindow #btnCancelar": {
                click: this.changePassCancelarClick
            }
        });
    }

});
